### ISSUE TITLE
Testing Components

### ISSUE THREAD

**Issue by mikeshams** [SREELAKSHMIKRISH/2021W_ESE-4009_2#1]
- Test WiFi module
- Test LDR
- Commit to your repository properly

**Comment by IndujaSudhish** [comment]
Testing of ESP8266 and LDR sensor

[issue solution.pptx](https://github.com/SREELAKSHMIKRISH/2021W_ESE-4009_2/files/6033217/issue.solution.pptx)

**Comment by IndujaSudhish** [comment]
The Assigned task testing of ESP8266 and LDR sensor are completed.
