### ISSUE TITLE
Schematic Diagram

### ISSUE THREAD

**Issue by mikeshams** [SREELAKSHMIKRISH/2021W_ESE-4009_2#2]
Based on the article, what points shall be considered to ensure our schematic diagram is error-free?

https://www.allaboutcircuits.com/technical-articles/error-checking-schematics/

**Comment by SREELAKSHMIKRISH** [comment]
Based on the article, I have listed some points on how to ensure that the schematic diagram is error free. I am attaching the file below . Thank you 
[Github word file.docx](https://github.com/SREELAKSHMIKRISH/2021W_ESE-4009_2/files/6050713/Github.word.file.docx)
