### ISSUE TITLE
Soil Moisture Sensor Interface

### ISSUE THREAD

**Issue by mikeshams** [SREELAKSHMIKRISH/2021W_ESE-4009_2#3]
Modify your code to see the results on one column!

**Comment by IndujaSudhish** [comment]
[issue.docx](https://github.com/SREELAKSHMIKRISH/2021W_ESE-4009_2/files/6091488/issue.docx)
To print the output in a column I have used \n command with printf in the code and it is specified in the file attached. The final result is also included in the file.
