### ISSUE TITLE
LDR Interface

### ISSUE THREAD

**Issue by mikeshams** [SREELAKSHMIKRISH/2021W_ESE-4009_2#4]
Convert the values to something meaningful and sensible for the end-user!

**Comment by SREELAKSHMIKRISH** [comment]
I have added some  more steps to the code to make the values more meaningful to the end-user. I used if-else statement in the code. The detailed answer with code is attached here. Thankyou.
[Github file #2 - Sreelakshmi Krishnankutty.docx](https://github.com/SREELAKSHMIKRISH/2021W_ESE-4009_2/files/6103252/Github.file.2.-.Sreelakshmi.Krishnankutty.docx)
