### ISSUE TITLE
Power Management

### ISSUE THREAD

**Issue by mikeshams** [SREELAKSHMIKRISH/2021W_ESE-4009_2#5]
Please review the following reference and explain if you can modify your task based on this reference or not!

"Power management is established by forcing the MCU into sleep mode. At the later stages the peripheral components will be staged to act according to the MCU status so that the peripherals may remain in a state of idle. Sleep mode is established by using rtcwake

SYNOPSIS:
rtcwake [options] [-d device] [-m standby_mode] {-s seconds|-t time_t}
 
https://manpages.debian.org/stretch/util-linux/rtcwake.8.en.html"

**Comment by SREELAKSHMIKRISH** [comment]
ANSWER:
The sleep mode of beagle bone can be attained in many methods. 

Here, In my presentation  used the method of making the beagle bone go to sleep mode and then waking it up after a certain time using the i2c lines, where, the PMIC and beagle bone black communicates using the i2c lines. It worked for my beaglebone and I was able to do it successfully.
Now I tried the rtcwake  function as per given in this reference and tried to run the command.
“rtcwake -d /dev/rtc0 -m standby -s 10” –  By using this command, I was able to make the beagle bone in sleep mode for 10 seconds and then it powers back up automatically after the 10 seconds.
We can change the time for sleep mode accordingly as per our needs. 
By using both methods, we can achieve the sleep mode of beagle bone black. 
I tried the rtcwake function before and I had some errors and was unable to wake the beagle bone black. But with this reference, I was able to do that successfully.


REFERENCE
(https://manpages.debian.org/stretch/util-linux/rtcwake.8.en.html)
